export const COUNTRIES = [
  {
    name: "Andorra",
    code: "AD",
    currency: "EUR",
    currencyName: "Euro",
    emoji: "🇦🇩",
  },
  {
    name: "United Arab Emirates",
    code: "AE",
    currency: "AED",
    currencyName: "United Arab Emirates Dirham",
    emoji: "🇦🇪",
  },
  {
    name: "Afghanistan",
    code: "AF",
    currency: "AFN",
    currencyName: "Afghan Afghani",
    emoji: "🇦🇫",
  },
  {
    name: "Albania",
    code: "AL",
    currency: "ALL",
    currencyName: "Albanian Lek",
    emoji: "🇦🇱",
  },
  {
    name: "Armenia",
    code: "AM",
    currency: "AMD",
    currencyName: "Armenian Dram",
    emoji: "🇦🇲",
  },
  {
    name: "Angola",
    code: "AO",
    currency: "AOA",
    currencyName: "Angolan Kwanza",
    emoji: "🇦🇴",
  },
  {
    name: "Argentina",
    code: "AR",
    currency: "ARS",
    currencyName: "Argentine Peso",
    emoji: "🇦🇷",
  },
  {
    name: "Austria",
    code: "AT",
    currency: "EUR",
    currencyName: "Euro",
    emoji: "🇦🇹",
  },
  {
    name: "Australia",
    code: "AU",
    currency: "AUD",
    currencyName: "Australian Dollar",
    emoji: "🇦🇺",
  },
  {
    name: "Azerbaijan",
    code: "AZ",
    currency: "AZN",
    currencyName: "Azerbaijani Manat",
    emoji: "🇦🇿",
  },
  {
    name: "Bosnia & Herzegovina",
    code: "BA",
    currency: "BAM",
    currencyName: "Bosnia-Herzegovina Convertible Mark",
    emoji: "🇧🇦",
  },
  {
    name: "Barbados",
    code: "BB",
    currency: "BBD",
    currencyName: "Barbadian Dollar",
    emoji: "🇧🇧",
  },
  {
    name: "Bangladesh",
    code: "BD",
    currency: "BDT",
    currencyName: "Bangladeshi Taka",
    emoji: "🇧🇩",
  },
  {
    name: "Belgium",
    code: "BE",
    currency: "EUR",
    currencyName: "Euro",
    emoji: "🇧🇪",
  },
  {
    name: "Burkina Faso",
    code: "BF",
    currency: "XOF",
    currencyName: "West African CFA Franc",
    emoji: "🇧🇫",
  },
  {
    name: "Bulgaria",
    code: "BG",
    currency: "BGN",
    currencyName: "Bulgarian Lev",
    emoji: "🇧🇬",
  },
  {
    name: "Bahrain",
    code: "BH",
    currency: "BHD",
    currencyName: "Bahraini Dinar",
    emoji: "🇧🇭",
  },
  {
    name: "Burundi",
    code: "BI",
    currency: "BIF",
    currencyName: "Burundian Franc",
    emoji: "🇧🇮",
  },
  {
    name: "Benin",
    code: "BJ",
    currency: "XOF",
    currencyName: "West African CFA Franc",
    emoji: "🇧🇯",
  },
  {
    name: "St. Barthélemy",
    code: "BL",
    currency: "EUR",
    currencyName: "Euro",
    emoji: "🇧🇱",
  },
  {
    name: "Brunei",
    code: "BN",
    currency: "BND",
    currencyName: "Brunei Dollar",
    emoji: "🇧🇳",
  },
  {
    name: "Bolivia",
    code: "BO",
    currency: "BOB",
    currencyName: "Bolivian Boliviano",
    emoji: "🇧🇴",
  },
  {
    name: "Brazil",
    code: "BR",
    currency: "BRL",
    currencyName: "Brazilian Real",
    emoji: "🇧🇷",
  },
  {
    name: "Bahamas",
    code: "BS",
    currency: "BSD",
    currencyName: "Bahamian Dollar",
    emoji: "🇧🇸",
  },
  {
    name: "Bhutan",
    code: "BT",
    currency: "BTN",
    currencyName: "Bhutanese Ngultrum",
    emoji: "🇧🇹",
  },
  {
    name: "Bouvet Island",
    code: "BV",
    currency: "NOK",
    currencyName: "Norwegian Krone",
    emoji: "🇧🇻",
  },
  {
    name: "Botswana",
    code: "BW",
    currency: "BWP",
    currencyName: "Botswana Pula",
    emoji: "🇧🇼",
  },
  {
    name: "Belarus",
    code: "BY",
    currency: "BYN",
    currencyName: "Belarusian Ruble",
    emoji: "🇧🇾",
  },
  {
    name: "Belize",
    code: "BZ",
    currency: "BZD",
    currencyName: "Belize Dollar",
    emoji: "🇧🇿",
  },
  {
    name: "Canada",
    code: "CA",
    currency: "CAD",
    currencyName: "Canadian Dollar",
    emoji: "🇨🇦",
  },
  {
    name: "Congo - Kinshasa",
    code: "CD",
    currency: "CDF",
    currencyName: "Congolese Franc",
    emoji: "🇨🇩",
  },
  {
    name: "Central African Republic",
    code: "CF",
    currency: "XAF",
    currencyName: "Central African CFA Franc",
    emoji: "🇨🇫",
  },
  {
    name: "Congo - Brazzaville",
    code: "CG",
    currency: "XAF",
    currencyName: "Central African CFA Franc",
    emoji: "🇨🇬",
  },
  {
    name: "Switzerland",
    code: "CH",
    currency: "CHF",
    currencyName: "Swiss Franc",
    emoji: "🇨🇭",
  },
  {
    name: "Côte d'Ivoire",
    code: "CI",
    currency: "XOF",
    currencyName: "West African CFA Franc",
    emoji: "🇨🇮",
  },
  {
    name: "Chile",
    code: "CL",
    currency: "CLP",
    currencyName: "Chilean Peso",
    emoji: "🇨🇱",
  },
  {
    name: "Cameroon",
    code: "CM",
    currency: "XAF",
    currencyName: "Central African CFA Franc",
    emoji: "🇨🇲",
  },
  {
    name: "China",
    code: "CN",
    currency: "CNY",
    currencyName: "Chinese Yuan",
    emoji: "🇨🇳",
  },
  {
    name: "Colombia",
    code: "CO",
    currency: "COP",
    currencyName: "Colombian Peso",
    emoji: "🇨🇴",
  },
  {
    name: "Costa Rica",
    code: "CR",
    currency: "CRC",
    currencyName: "Costa Rican Colon",
    emoji: "🇨🇷",
  },
  {
    name: "Cuba",
    code: "CU",
    currency: "CUP",
    currencyName: "Cuban Peso",
    emoji: "🇨🇺",
  },
  {
    name: "Cape Verde",
    code: "CV",
    currency: "CVE",
    currencyName: "Cape Verdean Escudo",
    emoji: "🇨🇻",
  },
  {
    name: "Cyprus",
    code: "CY",
    currency: "EUR",
    currencyName: "Euro",
    emoji: "🇨🇾",
  },
  {
    name: "Czechia",
    code: "CZ",
    currency: "CZK",
    currencyName: "Czech Koruna",
    emoji: "🇨🇿",
  },
  {
    name: "Germany",
    code: "DE",
    currency: "EUR",
    currencyName: "Euro",
    emoji: "🇩🇪",
  },
  {
    name: "Djibouti",
    code: "DJ",
    currency: "DJF",
    currencyName: "Djiboutian Franc",
    emoji: "🇩🇯",
  },
  {
    name: "Denmark",
    code: "DK",
    currency: "DKK",
    currencyName: "Danish Krone",
    emoji: "🇩🇰",
  },
  {
    name: "Dominica",
    code: "DM",
    currency: "XCD",
    currencyName: "East Caribbean Dollar",
    emoji: "🇩🇲",
  },
  {
    name: "Dominican Republic",
    code: "DO",
    currency: "DOP",
    currencyName: "Dominican Peso",
    emoji: "🇩🇴",
  },
  {
    name: "Algeria",
    code: "DZ",
    currency: "DZD",
    currencyName: "Algerian Dinar",
    emoji: "🇩🇿",
  },
  {
    name: "Ecuador",
    code: "EC",
    currency: "USD",
    currencyName: "United States Dollar",
    emoji: "🇪🇨",
  },
  {
    name: "Estonia",
    code: "EE",
    currency: "EUR",
    currencyName: "Euro",
    emoji: "🇪🇪",
  },
  {
    name: "Egypt",
    code: "EG",
    currency: "EGP",
    currencyName: "Egyptian Pound",
    emoji: "🇪🇬",
  },
  {
    name: "Eritrea",
    code: "ER",
    currency: "ERN",
    currencyName: "Eritrean Nakfa",
    emoji: "🇪🇷",
  },
  {
    name: "Spain",
    code: "ES",
    currency: "EUR",
    currencyName: "Euro",
    emoji: "🇪🇸",
  },
  {
    name: "Ethiopia",
    code: "ET",
    currency: "ETB",
    currencyName: "Ethiopian Birr",
    emoji: "🇪🇹",
  },
  {
    name: "Finland",
    code: "FI",
    currency: "EUR",
    currencyName: "Euro",
    emoji: "🇫🇮",
  },
  {
    name: "Fiji",
    code: "FJ",
    currency: "FJD",
    currencyName: "Fijian Dollar",
    emoji: "🇫🇯",
  },
  {
    name: "Micronesia",
    code: "FM",
    currency: "USD",
    currencyName: "United States Dollar",
    emoji: "🇫🇲",
  },
  {
    name: "France",
    code: "FR",
    currency: "EUR",
    currencyName: "Euro",
    emoji: "🇫🇷",
  },
  {
    name: "Gabon",
    code: "GA",
    currency: "XAF",
    currencyName: "Central African CFA Franc",
    emoji: "🇬🇦",
  },
  {
    name: "United Kingdom",
    code: "GB",
    currency: "GBP",
    currencyName: "British Pound Sterling",
    emoji: "🇬🇧",
  },
  {
    name: "Grenada",
    code: "GD",
    currency: "XCD",
    currencyName: "East Caribbean Dollar",
    emoji: "🇬🇩",
  },
  {
    name: "Georgia",
    code: "GE",
    currency: "GEL",
    currencyName: "Georgian Lari",
    emoji: "🇬🇪",
  },
  {
    name: "Ghana",
    code: "GH",
    currency: "GHS",
    currencyName: "Ghanaian Cedi",
    emoji: "🇬🇭",
  },
  {
    name: "Gambia",
    code: "GM",
    currency: "GMD",
    currencyName: "Gambian Dalasi",
    emoji: "🇬🇲",
  },
  {
    name: "Guinea",
    code: "GN",
    currency: "GNF",
    currencyName: "Guinean Franc",
    emoji: "🇬🇳",
  },
  {
    name: "Equatorial Guinea",
    code: "GQ",
    currency: "XAF",
    currencyName: "Central African CFA Franc",
    emoji: "🇬🇶",
  },
  {
    name: "Greece",
    code: "GR",
    currency: "EUR",
    currencyName: "Euro",
    emoji: "🇬🇷",
  },
  {
    name: "Guatemala",
    code: "GT",
    currency: "GTQ",
    currencyName: "Guatemalan Quetzal",
    emoji: "🇬🇹",
  },
  {
    name: "Guinea-Bissau",
    code: "GW",
    currency: "XOF",
    currencyName: "West African CFA Franc",
    emoji: "🇬🇼",
  },
  {
    name: "Guyana",
    code: "GY",
    currency: "GYD",
    currencyName: "Guyanese Dollar",
    emoji: "🇬🇾",
  },
  {
    name: "Hong Kong SAR China",
    code: "HK",
    currency: "HKD",
    currencyName: "Hong Kong Dollar",
    emoji: "🇭🇰",
  },
  {
    name: "Honduras",
    code: "HN",
    currency: "HNL",
    currencyName: "Honduran Lempira",
    emoji: "🇭🇳",
  },
  {
    name: "Croatia",
    code: "HR",
    currency: "EUR",
    currencyName: "Euro",
    emoji: "🇭🇷",
  },
  {
    name: "Haiti",
    code: "HT",
    currency: "HTG",
    currencyName: "Haitian Gourde",
    emoji: "🇭🇹",
  },
  {
    name: "Hungary",
    code: "HU",
    currency: "HUF",
    currencyName: "Hungarian Forint",
    emoji: "🇭🇺",
  },
  {
    name: "Indonesia",
    code: "ID",
    currency: "IDR",
    currencyName: "Indonesian Rupiah",
    emoji: "🇮🇩",
  },
  {
    name: "Ireland",
    code: "IE",
    currency: "EUR",
    currencyName: "Euro",
    emoji: "🇮🇪",
  },
  {
    name: "Israel",
    code: "IL",
    currency: "ILS",
    currencyName: "Israeli New Shekel",
    emoji: "🇮🇱",
  },
  {
    name: "India",
    code: "IN",
    currency: "INR",
    currencyName: "Indian Rupee",
    emoji: "🇮🇳",
  },
  {
    name: "Iraq",
    code: "IQ",
    currency: "IQD",
    currencyName: "Iraqi Dinar",
    emoji: "🇮🇶",
  },
  {
    name: "Iran",
    code: "IR",
    currency: "IRR",
    currencyName: "Iranian Rial",
    emoji: "🇮🇷",
  },
  {
    name: "Iceland",
    code: "IS",
    currency: "ISK",
    currencyName: "Icelandic Krona",
    emoji: "🇮🇸",
  },
  {
    name: "Italy",
    code: "IT",
    currency: "EUR",
    currencyName: "Euro",
    emoji: "🇮🇹",
  },
  {
    name: "Jamaica",
    code: "JM",
    currency: "JMD",
    currencyName: "Jamaican Dollar",
    emoji: "🇯🇲",
  },
  {
    name: "Jordan",
    code: "JO",
    currency: "JOD",
    currencyName: "Jordanian Dinar",
    emoji: "🇯🇴",
  },
  {
    name: "Japan",
    code: "JP",
    currency: "JPY",
    currencyName: "Japanese Yen",
    emoji: "🇯🇵",
  },
  {
    name: "Kenya",
    code: "KE",
    currency: "KES",
    currencyName: "Kenyan Shilling",
    emoji: "🇰🇪",
  },
  {
    name: "Kyrgyzstan",
    code: "KG",
    currency: "KGS",
    currencyName: "Kyrgyzstani Som",
    emoji: "🇰🇬",
  },
  {
    name: "Cambodia",
    code: "KH",
    currency: "KHR",
    currencyName: "Cambodian Riel",
    emoji: "🇰🇭",
  },
  {
    name: "Kiribati",
    code: "KI",
    currency: "AUD",
    currencyName: "Australian Dollar",
    emoji: "🇰🇮",
  },
  {
    name: "Comoros",
    code: "KM",
    currency: "KMF",
    currencyName: "Comorian Franc",
    emoji: "🇰🇲",
  },
  {
    name: "St. Kitts & Nevis",
    code: "KN",
    currency: "XCD",
    currencyName: "East Caribbean Dollar",
    emoji: "🇰🇳",
  },
  {
    name: "North Korea",
    code: "KP",
    currency: "KPW",
    currencyName: "North Korean Won",
    emoji: "🇰🇵",
  },
  {
    name: "South Korea",
    code: "KR",
    currency: "KRW",
    currencyName: "South Korean Won",
    emoji: "🇰🇷",
  },
  {
    name: "Kuwait",
    code: "KW",
    currency: "KWD",
    currencyName: "Kuwaiti Dinar",
    emoji: "🇰🇼",
  },
  {
    name: "Kazakhstan",
    code: "KZ",
    currency: "KZT",
    currencyName: "Kazakhstani Tenge",
    emoji: "🇰🇿",
  },
  {
    name: "Laos",
    code: "LA",
    currency: "LAK",
    currencyName: "Lao Kip",
    emoji: "🇱🇦",
  },
  {
    name: "Lebanon",
    code: "LB",
    currency: "LBP",
    currencyName: "Lebanese Pound",
    emoji: "🇱🇧",
  },
  {
    name: "St. Lucia",
    code: "LC",
    currency: "XCD",
    currencyName: "East Caribbean Dollar",
    emoji: "🇱🇨",
  },
  {
    name: "Liechtenstein",
    code: "LI",
    currency: "CHF",
    currencyName: "Swiss Franc",
    emoji: "🇱🇮",
  },
  {
    name: "Sri Lanka",
    code: "LK",
    currency: "LKR",
    currencyName: "Sri Lankan Rupee",
    emoji: "🇱🇰",
  },
  {
    name: "Liberia",
    code: "LR",
    currency: "LRD",
    currencyName: "Liberian Dollar",
    emoji: "🇱🇷",
  },
  {
    name: "Lesotho",
    code: "LS",
    currency: "LSL",
    currencyName: "Lesotho Loti",
    emoji: "🇱🇸",
  },
  {
    name: "Lithuania",
    code: "LT",
    currency: "EUR",
    currencyName: "Euro",
    emoji: "🇱🇹",
  },
  {
    name: "Luxembourg",
    code: "LU",
    currency: "EUR",
    currencyName: "Euro",
    emoji: "🇱🇺",
  },
  {
    name: "Latvia",
    code: "LV",
    currency: "EUR",
    currencyName: "Euro",
    emoji: "🇱🇻",
  },
  {
    name: "Libya",
    code: "LY",
    currency: "LYD",
    currencyName: "Libyan Dinar",
    emoji: "🇱🇾",
  },
  {
    name: "Morocco",
    code: "MA",
    currency: "MAD",
    currencyName: "Moroccan Dirham",
    emoji: "🇲🇦",
  },
  {
    name: "Monaco",
    code: "MC",
    currency: "EUR",
    currencyName: "Euro",
    emoji: "🇲🇨",
  },
  {
    name: "Moldova",
    code: "MD",
    currency: "MDL",
    currencyName: "Moldovan Leu",
    emoji: "🇲🇩",
  },
  {
    name: "Montenegro",
    code: "ME",
    currency: "EUR",
    currencyName: "Euro",
    emoji: "🇲🇪",
  },
  {
    name: "Madagascar",
    code: "MG",
    currency: "MGA",
    currencyName: "Malagasy Ariary",
    emoji: "🇲🇬",
  },
  {
    name: "Marshall Islands",
    code: "MH",
    currency: "USD",
    currencyName: "United States Dollar",
    emoji: "🇲🇭",
  },
  {
    name: "North Macedonia",
    code: "MK",
    currency: "MKD",
    currencyName: "Macedonian Denar",
    emoji: "🇲🇰",
  },
  {
    name: "Mali",
    code: "ML",
    currency: "XOF",
    currencyName: "West African CFA Franc",
    emoji: "🇲🇱",
  },
  {
    name: "Myanmar (Burma)",
    code: "MM",
    currency: "MMK",
    currencyName: "Myanmar Kyat",
    emoji: "🇲🇲",
  },
  {
    name: "Mongolia",
    code: "MN",
    currency: "MNT",
    currencyName: "Mongolian Tugrik",
    emoji: "🇲🇳",
  },
  {
    name: "Macao SAR China",
    code: "MO",
    currency: "MOP",
    currencyName: "Macanese Pataca",
    emoji: "🇲🇴",
  },
  {
    name: "Mauritania",
    code: "MR",
    currency: "MRU",
    currencyName: "Mauritanian Ouguiya",
    emoji: "🇲🇷",
  },
  {
    name: "Malta",
    code: "MT",
    currency: "EUR",
    currencyName: "Euro",
    emoji: "🇲🇹",
  },
  {
    name: "Mauritius",
    code: "MU",
    currency: "MUR",
    currencyName: "Mauritian Rupee",
    emoji: "🇲🇺",
  },
  {
    name: "Maldives",
    code: "MV",
    currency: "MVR",
    currencyName: "Maldivian Rufiyaa",
    emoji: "🇲🇻",
  },
  {
    name: "Malawi",
    code: "MW",
    currency: "MWK",
    currencyName: "Malawian Kwacha",
    emoji: "🇲🇼",
  },
  {
    name: "Mexico",
    code: "MX",
    currency: "MXN",
    currencyName: "Mexican Peso",
    emoji: "🇲🇽",
  },
  {
    name: "Malaysia",
    code: "MY",
    currency: "MYR",
    currencyName: "Malaysian Ringgit",
    emoji: "🇲🇾",
  },
  {
    name: "Mozambique",
    code: "MZ",
    currency: "MZN",
    currencyName: "Mozambican Metical",
    emoji: "🇲🇿",
  },
  {
    name: "Namibia",
    code: "NA",
    currency: "NAD",
    currencyName: "Namibian Dollar",
    emoji: "🇳🇦",
  },
  {
    name: "New Caledonia",
    code: "NC",
    currency: "XPF",
    currencyName: "CFP Franc",
    emoji: "🇳🇨",
  },
  {
    name: "Niger",
    code: "NE",
    currency: "XOF",
    currencyName: "West African CFA Franc",
    emoji: "🇳🇪",
  },
  {
    name: "Nigeria",
    code: "NG",
    currency: "NGN",
    currencyName: "Nigerian Naira",
    emoji: "🇳🇬",
  },
  {
    name: "Nicaragua",
    code: "NI",
    currency: "NIO",
    currencyName: "Nicaraguan Cordoba",
    emoji: "🇳🇮",
  },
  {
    name: "Netherlands",
    code: "NL",
    currency: "EUR",
    currencyName: "Euro",
    emoji: "🇳🇱",
  },
  {
    name: "Norway",
    code: "NO",
    currency: "NOK",
    currencyName: "Norwegian Krone",
    emoji: "🇳🇴",
  },
  {
    name: "Nepal",
    code: "NP",
    currency: "NPR",
    currencyName: "Nepalese Rupee",
    emoji: "🇳🇵",
  },
  {
    name: "Nauru",
    code: "NR",
    currency: "AUD",
    currencyName: "Australian Dollar",
    emoji: "🇳🇷",
  },
  {
    name: "New Zealand",
    code: "NZ",
    currency: "NZD",
    currencyName: "New Zealand Dollar",
    emoji: "🇳🇿",
  },
  {
    name: "Oman",
    code: "OM",
    currency: "OMR",
    currencyName: "Omani Rial",
    emoji: "🇴🇲",
  },
  {
    name: "Panama",
    code: "PA",
    currency: "PAB",
    currencyName: "Panamanian Balboa",
    emoji: "🇵🇦",
  },
  {
    name: "Peru",
    code: "PE",
    currency: "PEN",
    currencyName: "Peruvian Sol",
    emoji: "🇵🇪",
  },
  {
    name: "Papua New Guinea",
    code: "PG",
    currency: "PGK",
    currencyName: "Papua New Guinean Kina",
    emoji: "🇵🇬",
  },
  {
    name: "Philippines",
    code: "PH",
    currency: "PHP",
    currencyName: "Philippine Peso",
    emoji: "🇵🇭",
  },
  {
    name: "Pakistan",
    code: "PK",
    currency: "PKR",
    currencyName: "Pakistani Rupee",
    emoji: "🇵🇰",
  },
  {
    name: "Poland",
    code: "PL",
    currency: "PLN",
    currencyName: "Polish Zloty",
    emoji: "🇵🇱",
  },
  {
    name: "Palestine",
    code: "PS",
    currency: "ILS",
    currencyName: "Israeli New Shekel",
    emoji: "🇵🇸",
  },
  {
    name: "Portugal",
    code: "PT",
    currency: "EUR",
    currencyName: "Euro",
    emoji: "🇵🇹",
  },
  {
    name: "Palau",
    code: "PW",
    currency: "USD",
    currencyName: "United States Dollar",
    emoji: "🇵🇼",
  },
  {
    name: "Paraguay",
    code: "PY",
    currency: "PYG",
    currencyName: "Paraguayan Guarani",
    emoji: "🇵🇾",
  },
  {
    name: "Qatar",
    code: "QA",
    currency: "QAR",
    currencyName: "Qatari Riyal",
    emoji: "🇶🇦",
  },
  {
    name: "Réunion",
    code: "RE",
    currency: "EUR",
    currencyName: "Euro",
    emoji: "🇷🇪",
  },
  {
    name: "Romania",
    code: "RO",
    currency: "RON",
    currencyName: "Romanian Leu",
    emoji: "🇷🇴",
  },
  {
    name: "Serbia",
    code: "RS",
    currency: "RSD",
    currencyName: "Serbian Dinar",
    emoji: "🇷🇸",
  },
  {
    name: "Russia",
    code: "RU",
    currency: "RUB",
    currencyName: "Russian Ruble",
    emoji: "🇷🇺",
  },
  {
    name: "Rwanda",
    code: "RW",
    currency: "RWF",
    currencyName: "Rwandan Franc",
    emoji: "🇷🇼",
  },
  {
    name: "Saudi Arabia",
    code: "SA",
    currency: "SAR",
    currencyName: "Saudi Riyal",
    emoji: "🇸🇦",
  },
  {
    name: "Solomon Islands",
    code: "SB",
    currency: "SBD",
    currencyName: "Solomon Islands Dollar",
    emoji: "🇸🇧",
  },
  {
    name: "Seychelles",
    code: "SC",
    currency: "SCR",
    currencyName: "Seychellois Rupee",
    emoji: "🇸🇨",
  },
  {
    name: "Sudan",
    code: "SD",
    currency: "SDG",
    currencyName: "Sudanese Pound",
    emoji: "🇸🇩",
  },
  {
    name: "Sweden",
    code: "SE",
    currency: "SEK",
    currencyName: "Swedish Krona",
    emoji: "🇸🇪",
  },
  {
    name: "Singapore",
    code: "SG",
    currency: "SGD",
    currencyName: "Singapore Dollar",
    emoji: "🇸🇬",
  },
  {
    name: "Slovenia",
    code: "SI",
    currency: "EUR",
    currencyName: "Euro",
    emoji: "🇸🇮",
  },
  {
    name: "Slovakia",
    code: "SK",
    currency: "EUR",
    currencyName: "Euro",
    emoji: "🇸🇰",
  },
  {
    name: "Sierra Leone",
    code: "SL",
    currency: "SLE",
    currencyName: "Sierra Leonean Leone",
    emoji: "🇸🇱",
  },
  {
    name: "San Marino",
    code: "SM",
    currency: "EUR",
    currencyName: "Euro",
    emoji: "🇸🇲",
  },
  {
    name: "Senegal",
    code: "SN",
    currency: "XOF",
    currencyName: "West African CFA Franc",
    emoji: "🇸🇳",
  },
  {
    name: "Somalia",
    code: "SO",
    currency: "SOS",
    currencyName: "Somali Shilling",
    emoji: "🇸🇴",
  },
  {
    name: "Suriname",
    code: "SR",
    currency: "SRD",
    currencyName: "Surinamese Dollar",
    emoji: "🇸🇷",
  },
  {
    name: "South Sudan",
    code: "SS",
    currency: "SSP",
    currencyName: "South Sudanese Pound",
    emoji: "🇸🇸",
  },
  {
    name: "São Tomé & Príncipe",
    code: "ST",
    currency: "STN",
    currencyName: "Sao Tome and Principe Dobra",
    emoji: "🇸🇹",
  },
  {
    name: "El Salvador",
    code: "SV",
    currency: "USD",
    currencyName: "United States Dollar",
    emoji: "🇸🇻",
  },
  {
    name: "Syria",
    code: "SY",
    currency: "SYP",
    currencyName: "Syrian Pound",
    emoji: "🇸🇾",
  },
  {
    name: "Eswatini",
    code: "SZ",
    currency: "SZL",
    currencyName: "Swazi Lilangeni",
    emoji: "🇸🇿",
  },
  {
    name: "Chad",
    code: "TD",
    currency: "XAF",
    currencyName: "Central African CFA Franc",
    emoji: "🇹🇩",
  },
  {
    name: "Togo",
    code: "TG",
    currency: "XOF",
    currencyName: "West African CFA Franc",
    emoji: "🇹🇬",
  },
  {
    name: "Thailand",
    code: "TH",
    currency: "THB",
    currencyName: "Thai Baht",
    emoji: "🇹🇭",
  },
  {
    name: "Tajikistan",
    code: "TJ",
    currency: "TJS",
    currencyName: "Tajikistani Somoni",
    emoji: "🇹🇯",
  },
  {
    name: "Timor-Leste",
    code: "TL",
    currency: "USD",
    currencyName: "United States Dollar",
    emoji: "🇹🇱",
  },
  {
    name: "Turkmenistan",
    code: "TM",
    currency: "TMT",
    currencyName: "Turkmenistani Manat",
    emoji: "🇹🇲",
  },
  {
    name: "Tunisia",
    code: "TN",
    currency: "TND",
    currencyName: "Tunisian Dinar",
    emoji: "🇹🇳",
  },
  {
    name: "Tonga",
    code: "TO",
    currency: "TOP",
    currencyName: "Tongan Paanga",
    emoji: "🇹🇴",
  },
  {
    name: "Turkey",
    code: "TR",
    currency: "TRY",
    currencyName: "Turkish Lira",
    emoji: "🇹🇷",
  },
  {
    name: "Trinidad & Tobago",
    code: "TT",
    currency: "TTD",
    currencyName: "Trinidad and Tobago Dollar",
    emoji: "🇹🇹",
  },
  {
    name: "Tuvalu",
    code: "TV",
    currency: "AUD",
    currencyName: "Australian Dollar",
    emoji: "🇹🇻",
  },
  {
    name: "Taiwan",
    code: "TW",
    currency: "TWD",
    currencyName: "New Taiwan Dollar",
    emoji: "🇹🇼",
  },
  {
    name: "Tanzania",
    code: "TZ",
    currency: "TZS",
    currencyName: "Tanzanian Shilling",
    emoji: "🇹🇿",
  },
  {
    name: "Ukraine",
    code: "UA",
    currency: "UAH",
    currencyName: "Ukrainian Hryvnia",
    emoji: "🇺🇦",
  },
  {
    name: "Uganda",
    code: "UG",
    currency: "UGX",
    currencyName: "Ugandan Shilling",
    emoji: "🇺🇬",
  },
  {
    name: "United States",
    code: "US",
    currency: "USD",
    currencyName: "United States Dollar",
    emoji: "🇺🇸",
  },
  {
    name: "Uruguay",
    code: "UY",
    currency: "UYU",
    currencyName: "Uruguayan Peso",
    emoji: "🇺🇾",
  },
  {
    name: "Uzbekistan",
    code: "UZ",
    currency: "UZS",
    currencyName: "Uzbekistani Som",
    emoji: "🇺🇿",
  },
  {
    name: "Vatican City",
    code: "VA",
    currency: "EUR",
    currencyName: "Euro",
    emoji: "🇻🇦",
  },
  {
    name: "St. Vincent & Grenadines",
    code: "VC",
    currency: "XCD",
    currencyName: "East Caribbean Dollar",
    emoji: "🇻🇨",
  },
  {
    name: "Venezuela",
    code: "VE",
    currency: "VES",
    currencyName: "Venezuelan Bolivar Soberano",
    emoji: "🇻🇪",
  },
  {
    name: "Vietnam",
    code: "VN",
    currency: "VND",
    currencyName: "Vietnamese Dong",
    emoji: "🇻🇳",
  },
  {
    name: "Vanuatu",
    code: "VU",
    currency: "VUV",
    currencyName: "Vanuatu Vatu",
    emoji: "🇻🇺",
  },
  {
    name: "Samoa",
    code: "WS",
    currency: "WST",
    currencyName: "Samoan Tala",
    emoji: "🇼🇸",
  },
  {
    name: "Yemen",
    code: "YE",
    currency: "YER",
    currencyName: "Yemeni Rial",
    emoji: "🇾🇪",
  },
  {
    name: "South Africa",
    code: "ZA",
    currency: "ZAR",
    currencyName: "South African Rand",
    emoji: "🇿🇦",
  },
  {
    name: "Zambia",
    code: "ZM",
    currency: "ZMW",
    currencyName: "Zambian Kwacha",
    emoji: "🇿🇲",
  },
  {
    name: "Zimbabwe",
    code: "ZW",
    currency: "USD",
    currencyName: "United States Dollar",
    emoji: "🇿🇼",
  },
  {
    name: "England",
    code: "ENGLAND",
    currency: "GBP",
    currencyName: "British Pound Sterling",
    emoji: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  },
  {
    name: "Scotland",
    code: "SCOTLAND",
    currency: "GBP",
    currencyName: "British Pound Sterling",
    emoji: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  },
  {
    name: "Wales",
    code: "WALES",
    currency: "GBP",
    currencyName: "British Pound Sterling",
    emoji: "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
  },
] as {
  name: string
  code: string
  currency: string
  currencyName: string
  emoji: string
}[]

export function getCurrencyForCountry(countryCode: string): string | undefined {
  return COUNTRIES.find((c) => c.code === countryCode)?.currency
}

// Derive unique currencies from countries, with a representative flag for each
export const CURRENCIES = (() => {
  const seen = new Map<string, { code: string; name: string; emoji: string }>()
  for (const country of COUNTRIES) {
    if (!seen.has(country.currency)) {
      seen.set(country.currency, {
        code: country.currency,
        name: country.currencyName,
        emoji: country.emoji,
      })
    }
  }
  return Array.from(seen.values()).sort((a, b) => a.code.localeCompare(b.code))
})()
