/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CreateOrgRouteImport } from './routes/create-org'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppTestRouteRouteImport } from './routes/_app/test-route'
import { Route as AppAllProjectsRouteImport } from './routes/_app/all-projects'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as AppProjectIdRouteImport } from './routes/_app/project.$id'
import { Route as AppPackageIdRouteImport } from './routes/_app/package.$id'
import { Route as AppProjectIdIndexRouteImport } from './routes/_app/project.$id.index'
import { Route as AppPackageIdIndexRouteImport } from './routes/_app/package.$id.index'
import { Route as AppPackageIdTechRouteImport } from './routes/_app/package.$id.tech'
import { Route as AppPackageIdCommIndexRouteImport } from './routes/_app/package.$id.comm.index'
import { Route as AppPackageIdCommAssetIdRouteImport } from './routes/_app/package.$id.comm.$assetId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateOrgRoute = CreateOrgRouteImport.update({
  id: '/create-org',
  path: '/create-org',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTestRouteRoute = AppTestRouteRouteImport.update({
  id: '/test-route',
  path: '/test-route',
  getParentRoute: () => AppRoute,
} as any)
const AppAllProjectsRoute = AppAllProjectsRouteImport.update({
  id: '/all-projects',
  path: '/all-projects',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProjectIdRoute = AppProjectIdRouteImport.update({
  id: '/project/$id',
  path: '/project/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppPackageIdRoute = AppPackageIdRouteImport.update({
  id: '/package/$id',
  path: '/package/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectIdIndexRoute = AppProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProjectIdRoute,
} as any)
const AppPackageIdIndexRoute = AppPackageIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPackageIdRoute,
} as any)
const AppPackageIdTechRoute = AppPackageIdTechRouteImport.update({
  id: '/tech',
  path: '/tech',
  getParentRoute: () => AppPackageIdRoute,
} as any)
const AppPackageIdCommIndexRoute = AppPackageIdCommIndexRouteImport.update({
  id: '/comm/',
  path: '/comm/',
  getParentRoute: () => AppPackageIdRoute,
} as any)
const AppPackageIdCommAssetIdRoute = AppPackageIdCommAssetIdRouteImport.update({
  id: '/comm/$assetId',
  path: '/comm/$assetId',
  getParentRoute: () => AppPackageIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/create-org': typeof CreateOrgRoute
  '/login': typeof LoginRoute
  '/admin': typeof AppAdminRoute
  '/all-projects': typeof AppAllProjectsRoute
  '/test-route': typeof AppTestRouteRoute
  '/': typeof AppIndexRoute
  '/package/$id': typeof AppPackageIdRouteWithChildren
  '/project/$id': typeof AppProjectIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/package/$id/tech': typeof AppPackageIdTechRoute
  '/package/$id/': typeof AppPackageIdIndexRoute
  '/project/$id/': typeof AppProjectIdIndexRoute
  '/package/$id/comm/$assetId': typeof AppPackageIdCommAssetIdRoute
  '/package/$id/comm': typeof AppPackageIdCommIndexRoute
}
export interface FileRoutesByTo {
  '/create-org': typeof CreateOrgRoute
  '/login': typeof LoginRoute
  '/admin': typeof AppAdminRoute
  '/all-projects': typeof AppAllProjectsRoute
  '/test-route': typeof AppTestRouteRoute
  '/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/package/$id/tech': typeof AppPackageIdTechRoute
  '/package/$id': typeof AppPackageIdIndexRoute
  '/project/$id': typeof AppProjectIdIndexRoute
  '/package/$id/comm/$assetId': typeof AppPackageIdCommAssetIdRoute
  '/package/$id/comm': typeof AppPackageIdCommIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/create-org': typeof CreateOrgRoute
  '/login': typeof LoginRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/all-projects': typeof AppAllProjectsRoute
  '/_app/test-route': typeof AppTestRouteRoute
  '/_app/': typeof AppIndexRoute
  '/_app/package/$id': typeof AppPackageIdRouteWithChildren
  '/_app/project/$id': typeof AppProjectIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/package/$id/tech': typeof AppPackageIdTechRoute
  '/_app/package/$id/': typeof AppPackageIdIndexRoute
  '/_app/project/$id/': typeof AppProjectIdIndexRoute
  '/_app/package/$id/comm/$assetId': typeof AppPackageIdCommAssetIdRoute
  '/_app/package/$id/comm/': typeof AppPackageIdCommIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/create-org'
    | '/login'
    | '/admin'
    | '/all-projects'
    | '/test-route'
    | '/'
    | '/package/$id'
    | '/project/$id'
    | '/api/auth/$'
    | '/package/$id/tech'
    | '/package/$id/'
    | '/project/$id/'
    | '/package/$id/comm/$assetId'
    | '/package/$id/comm'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/create-org'
    | '/login'
    | '/admin'
    | '/all-projects'
    | '/test-route'
    | '/'
    | '/api/auth/$'
    | '/package/$id/tech'
    | '/package/$id'
    | '/project/$id'
    | '/package/$id/comm/$assetId'
    | '/package/$id/comm'
  id:
    | '__root__'
    | '/_app'
    | '/create-org'
    | '/login'
    | '/_app/admin'
    | '/_app/all-projects'
    | '/_app/test-route'
    | '/_app/'
    | '/_app/package/$id'
    | '/_app/project/$id'
    | '/api/auth/$'
    | '/_app/package/$id/tech'
    | '/_app/package/$id/'
    | '/_app/project/$id/'
    | '/_app/package/$id/comm/$assetId'
    | '/_app/package/$id/comm/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  CreateOrgRoute: typeof CreateOrgRoute
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-org': {
      id: '/create-org'
      path: '/create-org'
      fullPath: '/create-org'
      preLoaderRoute: typeof CreateOrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/test-route': {
      id: '/_app/test-route'
      path: '/test-route'
      fullPath: '/test-route'
      preLoaderRoute: typeof AppTestRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/all-projects': {
      id: '/_app/all-projects'
      path: '/all-projects'
      fullPath: '/all-projects'
      preLoaderRoute: typeof AppAllProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/project/$id': {
      id: '/_app/project/$id'
      path: '/project/$id'
      fullPath: '/project/$id'
      preLoaderRoute: typeof AppProjectIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/package/$id': {
      id: '/_app/package/$id'
      path: '/package/$id'
      fullPath: '/package/$id'
      preLoaderRoute: typeof AppPackageIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/project/$id/': {
      id: '/_app/project/$id/'
      path: '/'
      fullPath: '/project/$id/'
      preLoaderRoute: typeof AppProjectIdIndexRouteImport
      parentRoute: typeof AppProjectIdRoute
    }
    '/_app/package/$id/': {
      id: '/_app/package/$id/'
      path: '/'
      fullPath: '/package/$id/'
      preLoaderRoute: typeof AppPackageIdIndexRouteImport
      parentRoute: typeof AppPackageIdRoute
    }
    '/_app/package/$id/tech': {
      id: '/_app/package/$id/tech'
      path: '/tech'
      fullPath: '/package/$id/tech'
      preLoaderRoute: typeof AppPackageIdTechRouteImport
      parentRoute: typeof AppPackageIdRoute
    }
    '/_app/package/$id/comm/': {
      id: '/_app/package/$id/comm/'
      path: '/comm'
      fullPath: '/package/$id/comm'
      preLoaderRoute: typeof AppPackageIdCommIndexRouteImport
      parentRoute: typeof AppPackageIdRoute
    }
    '/_app/package/$id/comm/$assetId': {
      id: '/_app/package/$id/comm/$assetId'
      path: '/comm/$assetId'
      fullPath: '/package/$id/comm/$assetId'
      preLoaderRoute: typeof AppPackageIdCommAssetIdRouteImport
      parentRoute: typeof AppPackageIdRoute
    }
  }
}

interface AppPackageIdRouteChildren {
  AppPackageIdTechRoute: typeof AppPackageIdTechRoute
  AppPackageIdIndexRoute: typeof AppPackageIdIndexRoute
  AppPackageIdCommAssetIdRoute: typeof AppPackageIdCommAssetIdRoute
  AppPackageIdCommIndexRoute: typeof AppPackageIdCommIndexRoute
}

const AppPackageIdRouteChildren: AppPackageIdRouteChildren = {
  AppPackageIdTechRoute: AppPackageIdTechRoute,
  AppPackageIdIndexRoute: AppPackageIdIndexRoute,
  AppPackageIdCommAssetIdRoute: AppPackageIdCommAssetIdRoute,
  AppPackageIdCommIndexRoute: AppPackageIdCommIndexRoute,
}

const AppPackageIdRouteWithChildren = AppPackageIdRoute._addFileChildren(
  AppPackageIdRouteChildren,
)

interface AppProjectIdRouteChildren {
  AppProjectIdIndexRoute: typeof AppProjectIdIndexRoute
}

const AppProjectIdRouteChildren: AppProjectIdRouteChildren = {
  AppProjectIdIndexRoute: AppProjectIdIndexRoute,
}

const AppProjectIdRouteWithChildren = AppProjectIdRoute._addFileChildren(
  AppProjectIdRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAllProjectsRoute: typeof AppAllProjectsRoute
  AppTestRouteRoute: typeof AppTestRouteRoute
  AppIndexRoute: typeof AppIndexRoute
  AppPackageIdRoute: typeof AppPackageIdRouteWithChildren
  AppProjectIdRoute: typeof AppProjectIdRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAllProjectsRoute: AppAllProjectsRoute,
  AppTestRouteRoute: AppTestRouteRoute,
  AppIndexRoute: AppIndexRoute,
  AppPackageIdRoute: AppPackageIdRouteWithChildren,
  AppProjectIdRoute: AppProjectIdRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  CreateOrgRoute: CreateOrgRoute,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
