/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CreateOrgRouteImport } from './routes/create-org'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppVendorDbRouteImport } from './routes/_app/vendor-db'
import { Route as AppAllProjectsRouteImport } from './routes/_app/all-projects'
import { Route as ApiWorkosCallbackRouteImport } from './routes/api/workos.callback'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as AppProjectIdRouteImport } from './routes/_app/project.$id'
import { Route as AppPackageIdRouteImport } from './routes/_app/package.$id'
import { Route as AppPackageIdIndexRouteImport } from './routes/_app/package.$id.index'
import { Route as AppPackageIdTechRouteImport } from './routes/_app/package.$id.tech'
import { Route as AppPackageIdCommRouteImport } from './routes/_app/package.$id.comm'
import { Route as AppPackageIdTechIndexRouteImport } from './routes/_app/package.$id.tech.index'
import { Route as AppPackageIdCommIndexRouteImport } from './routes/_app/package.$id.comm.index'
import { Route as AppPackageIdTechPtcRouteImport } from './routes/_app/package.$id.tech.ptc'
import { Route as AppPackageIdTechDocsRouteImport } from './routes/_app/package.$id.tech.docs'
import { Route as AppPackageIdCommAssetIdRouteImport } from './routes/_app/package.$id.comm.$assetId'
import { Route as AppPackageIdCommAssetIdIndexRouteImport } from './routes/_app/package.$id.comm.$assetId.index'
import { Route as AppPackageIdCommAssetIdPtcRouteImport } from './routes/_app/package.$id.comm.$assetId.ptc'
import { Route as AppPackageIdCommAssetIdDocsRouteImport } from './routes/_app/package.$id.comm.$assetId.docs'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateOrgRoute = CreateOrgRouteImport.update({
  id: '/create-org',
  path: '/create-org',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppVendorDbRoute = AppVendorDbRouteImport.update({
  id: '/vendor-db',
  path: '/vendor-db',
  getParentRoute: () => AppRoute,
} as any)
const AppAllProjectsRoute = AppAllProjectsRouteImport.update({
  id: '/all-projects',
  path: '/all-projects',
  getParentRoute: () => AppRoute,
} as any)
const ApiWorkosCallbackRoute = ApiWorkosCallbackRouteImport.update({
  id: '/api/workos/callback',
  path: '/api/workos/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProjectIdRoute = AppProjectIdRouteImport.update({
  id: '/project/$id',
  path: '/project/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppPackageIdRoute = AppPackageIdRouteImport.update({
  id: '/package/$id',
  path: '/package/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppPackageIdIndexRoute = AppPackageIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPackageIdRoute,
} as any)
const AppPackageIdTechRoute = AppPackageIdTechRouteImport.update({
  id: '/tech',
  path: '/tech',
  getParentRoute: () => AppPackageIdRoute,
} as any)
const AppPackageIdCommRoute = AppPackageIdCommRouteImport.update({
  id: '/comm',
  path: '/comm',
  getParentRoute: () => AppPackageIdRoute,
} as any)
const AppPackageIdTechIndexRoute = AppPackageIdTechIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPackageIdTechRoute,
} as any)
const AppPackageIdCommIndexRoute = AppPackageIdCommIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPackageIdCommRoute,
} as any)
const AppPackageIdTechPtcRoute = AppPackageIdTechPtcRouteImport.update({
  id: '/ptc',
  path: '/ptc',
  getParentRoute: () => AppPackageIdTechRoute,
} as any)
const AppPackageIdTechDocsRoute = AppPackageIdTechDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => AppPackageIdTechRoute,
} as any)
const AppPackageIdCommAssetIdRoute = AppPackageIdCommAssetIdRouteImport.update({
  id: '/$assetId',
  path: '/$assetId',
  getParentRoute: () => AppPackageIdCommRoute,
} as any)
const AppPackageIdCommAssetIdIndexRoute =
  AppPackageIdCommAssetIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppPackageIdCommAssetIdRoute,
  } as any)
const AppPackageIdCommAssetIdPtcRoute =
  AppPackageIdCommAssetIdPtcRouteImport.update({
    id: '/ptc',
    path: '/ptc',
    getParentRoute: () => AppPackageIdCommAssetIdRoute,
  } as any)
const AppPackageIdCommAssetIdDocsRoute =
  AppPackageIdCommAssetIdDocsRouteImport.update({
    id: '/docs',
    path: '/docs',
    getParentRoute: () => AppPackageIdCommAssetIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/create-org': typeof CreateOrgRoute
  '/login': typeof LoginRoute
  '/all-projects': typeof AppAllProjectsRoute
  '/vendor-db': typeof AppVendorDbRoute
  '/': typeof AppIndexRoute
  '/package/$id': typeof AppPackageIdRouteWithChildren
  '/project/$id': typeof AppProjectIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/workos/callback': typeof ApiWorkosCallbackRoute
  '/package/$id/comm': typeof AppPackageIdCommRouteWithChildren
  '/package/$id/tech': typeof AppPackageIdTechRouteWithChildren
  '/package/$id/': typeof AppPackageIdIndexRoute
  '/package/$id/comm/$assetId': typeof AppPackageIdCommAssetIdRouteWithChildren
  '/package/$id/tech/docs': typeof AppPackageIdTechDocsRoute
  '/package/$id/tech/ptc': typeof AppPackageIdTechPtcRoute
  '/package/$id/comm/': typeof AppPackageIdCommIndexRoute
  '/package/$id/tech/': typeof AppPackageIdTechIndexRoute
  '/package/$id/comm/$assetId/docs': typeof AppPackageIdCommAssetIdDocsRoute
  '/package/$id/comm/$assetId/ptc': typeof AppPackageIdCommAssetIdPtcRoute
  '/package/$id/comm/$assetId/': typeof AppPackageIdCommAssetIdIndexRoute
}
export interface FileRoutesByTo {
  '/create-org': typeof CreateOrgRoute
  '/login': typeof LoginRoute
  '/all-projects': typeof AppAllProjectsRoute
  '/vendor-db': typeof AppVendorDbRoute
  '/': typeof AppIndexRoute
  '/project/$id': typeof AppProjectIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/workos/callback': typeof ApiWorkosCallbackRoute
  '/package/$id': typeof AppPackageIdIndexRoute
  '/package/$id/tech/docs': typeof AppPackageIdTechDocsRoute
  '/package/$id/tech/ptc': typeof AppPackageIdTechPtcRoute
  '/package/$id/comm': typeof AppPackageIdCommIndexRoute
  '/package/$id/tech': typeof AppPackageIdTechIndexRoute
  '/package/$id/comm/$assetId/docs': typeof AppPackageIdCommAssetIdDocsRoute
  '/package/$id/comm/$assetId/ptc': typeof AppPackageIdCommAssetIdPtcRoute
  '/package/$id/comm/$assetId': typeof AppPackageIdCommAssetIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/create-org': typeof CreateOrgRoute
  '/login': typeof LoginRoute
  '/_app/all-projects': typeof AppAllProjectsRoute
  '/_app/vendor-db': typeof AppVendorDbRoute
  '/_app/': typeof AppIndexRoute
  '/_app/package/$id': typeof AppPackageIdRouteWithChildren
  '/_app/project/$id': typeof AppProjectIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/workos/callback': typeof ApiWorkosCallbackRoute
  '/_app/package/$id/comm': typeof AppPackageIdCommRouteWithChildren
  '/_app/package/$id/tech': typeof AppPackageIdTechRouteWithChildren
  '/_app/package/$id/': typeof AppPackageIdIndexRoute
  '/_app/package/$id/comm/$assetId': typeof AppPackageIdCommAssetIdRouteWithChildren
  '/_app/package/$id/tech/docs': typeof AppPackageIdTechDocsRoute
  '/_app/package/$id/tech/ptc': typeof AppPackageIdTechPtcRoute
  '/_app/package/$id/comm/': typeof AppPackageIdCommIndexRoute
  '/_app/package/$id/tech/': typeof AppPackageIdTechIndexRoute
  '/_app/package/$id/comm/$assetId/docs': typeof AppPackageIdCommAssetIdDocsRoute
  '/_app/package/$id/comm/$assetId/ptc': typeof AppPackageIdCommAssetIdPtcRoute
  '/_app/package/$id/comm/$assetId/': typeof AppPackageIdCommAssetIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/create-org'
    | '/login'
    | '/all-projects'
    | '/vendor-db'
    | '/'
    | '/package/$id'
    | '/project/$id'
    | '/api/auth/$'
    | '/api/workos/callback'
    | '/package/$id/comm'
    | '/package/$id/tech'
    | '/package/$id/'
    | '/package/$id/comm/$assetId'
    | '/package/$id/tech/docs'
    | '/package/$id/tech/ptc'
    | '/package/$id/comm/'
    | '/package/$id/tech/'
    | '/package/$id/comm/$assetId/docs'
    | '/package/$id/comm/$assetId/ptc'
    | '/package/$id/comm/$assetId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/create-org'
    | '/login'
    | '/all-projects'
    | '/vendor-db'
    | '/'
    | '/project/$id'
    | '/api/auth/$'
    | '/api/workos/callback'
    | '/package/$id'
    | '/package/$id/tech/docs'
    | '/package/$id/tech/ptc'
    | '/package/$id/comm'
    | '/package/$id/tech'
    | '/package/$id/comm/$assetId/docs'
    | '/package/$id/comm/$assetId/ptc'
    | '/package/$id/comm/$assetId'
  id:
    | '__root__'
    | '/_app'
    | '/create-org'
    | '/login'
    | '/_app/all-projects'
    | '/_app/vendor-db'
    | '/_app/'
    | '/_app/package/$id'
    | '/_app/project/$id'
    | '/api/auth/$'
    | '/api/workos/callback'
    | '/_app/package/$id/comm'
    | '/_app/package/$id/tech'
    | '/_app/package/$id/'
    | '/_app/package/$id/comm/$assetId'
    | '/_app/package/$id/tech/docs'
    | '/_app/package/$id/tech/ptc'
    | '/_app/package/$id/comm/'
    | '/_app/package/$id/tech/'
    | '/_app/package/$id/comm/$assetId/docs'
    | '/_app/package/$id/comm/$assetId/ptc'
    | '/_app/package/$id/comm/$assetId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  CreateOrgRoute: typeof CreateOrgRoute
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiWorkosCallbackRoute: typeof ApiWorkosCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-org': {
      id: '/create-org'
      path: '/create-org'
      fullPath: '/create-org'
      preLoaderRoute: typeof CreateOrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vendor-db': {
      id: '/_app/vendor-db'
      path: '/vendor-db'
      fullPath: '/vendor-db'
      preLoaderRoute: typeof AppVendorDbRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/all-projects': {
      id: '/_app/all-projects'
      path: '/all-projects'
      fullPath: '/all-projects'
      preLoaderRoute: typeof AppAllProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/workos/callback': {
      id: '/api/workos/callback'
      path: '/api/workos/callback'
      fullPath: '/api/workos/callback'
      preLoaderRoute: typeof ApiWorkosCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/project/$id': {
      id: '/_app/project/$id'
      path: '/project/$id'
      fullPath: '/project/$id'
      preLoaderRoute: typeof AppProjectIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/package/$id': {
      id: '/_app/package/$id'
      path: '/package/$id'
      fullPath: '/package/$id'
      preLoaderRoute: typeof AppPackageIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/package/$id/': {
      id: '/_app/package/$id/'
      path: '/'
      fullPath: '/package/$id/'
      preLoaderRoute: typeof AppPackageIdIndexRouteImport
      parentRoute: typeof AppPackageIdRoute
    }
    '/_app/package/$id/tech': {
      id: '/_app/package/$id/tech'
      path: '/tech'
      fullPath: '/package/$id/tech'
      preLoaderRoute: typeof AppPackageIdTechRouteImport
      parentRoute: typeof AppPackageIdRoute
    }
    '/_app/package/$id/comm': {
      id: '/_app/package/$id/comm'
      path: '/comm'
      fullPath: '/package/$id/comm'
      preLoaderRoute: typeof AppPackageIdCommRouteImport
      parentRoute: typeof AppPackageIdRoute
    }
    '/_app/package/$id/tech/': {
      id: '/_app/package/$id/tech/'
      path: '/'
      fullPath: '/package/$id/tech/'
      preLoaderRoute: typeof AppPackageIdTechIndexRouteImport
      parentRoute: typeof AppPackageIdTechRoute
    }
    '/_app/package/$id/comm/': {
      id: '/_app/package/$id/comm/'
      path: '/'
      fullPath: '/package/$id/comm/'
      preLoaderRoute: typeof AppPackageIdCommIndexRouteImport
      parentRoute: typeof AppPackageIdCommRoute
    }
    '/_app/package/$id/tech/ptc': {
      id: '/_app/package/$id/tech/ptc'
      path: '/ptc'
      fullPath: '/package/$id/tech/ptc'
      preLoaderRoute: typeof AppPackageIdTechPtcRouteImport
      parentRoute: typeof AppPackageIdTechRoute
    }
    '/_app/package/$id/tech/docs': {
      id: '/_app/package/$id/tech/docs'
      path: '/docs'
      fullPath: '/package/$id/tech/docs'
      preLoaderRoute: typeof AppPackageIdTechDocsRouteImport
      parentRoute: typeof AppPackageIdTechRoute
    }
    '/_app/package/$id/comm/$assetId': {
      id: '/_app/package/$id/comm/$assetId'
      path: '/$assetId'
      fullPath: '/package/$id/comm/$assetId'
      preLoaderRoute: typeof AppPackageIdCommAssetIdRouteImport
      parentRoute: typeof AppPackageIdCommRoute
    }
    '/_app/package/$id/comm/$assetId/': {
      id: '/_app/package/$id/comm/$assetId/'
      path: '/'
      fullPath: '/package/$id/comm/$assetId/'
      preLoaderRoute: typeof AppPackageIdCommAssetIdIndexRouteImport
      parentRoute: typeof AppPackageIdCommAssetIdRoute
    }
    '/_app/package/$id/comm/$assetId/ptc': {
      id: '/_app/package/$id/comm/$assetId/ptc'
      path: '/ptc'
      fullPath: '/package/$id/comm/$assetId/ptc'
      preLoaderRoute: typeof AppPackageIdCommAssetIdPtcRouteImport
      parentRoute: typeof AppPackageIdCommAssetIdRoute
    }
    '/_app/package/$id/comm/$assetId/docs': {
      id: '/_app/package/$id/comm/$assetId/docs'
      path: '/docs'
      fullPath: '/package/$id/comm/$assetId/docs'
      preLoaderRoute: typeof AppPackageIdCommAssetIdDocsRouteImport
      parentRoute: typeof AppPackageIdCommAssetIdRoute
    }
  }
}

interface AppPackageIdCommAssetIdRouteChildren {
  AppPackageIdCommAssetIdDocsRoute: typeof AppPackageIdCommAssetIdDocsRoute
  AppPackageIdCommAssetIdPtcRoute: typeof AppPackageIdCommAssetIdPtcRoute
  AppPackageIdCommAssetIdIndexRoute: typeof AppPackageIdCommAssetIdIndexRoute
}

const AppPackageIdCommAssetIdRouteChildren: AppPackageIdCommAssetIdRouteChildren =
  {
    AppPackageIdCommAssetIdDocsRoute: AppPackageIdCommAssetIdDocsRoute,
    AppPackageIdCommAssetIdPtcRoute: AppPackageIdCommAssetIdPtcRoute,
    AppPackageIdCommAssetIdIndexRoute: AppPackageIdCommAssetIdIndexRoute,
  }

const AppPackageIdCommAssetIdRouteWithChildren =
  AppPackageIdCommAssetIdRoute._addFileChildren(
    AppPackageIdCommAssetIdRouteChildren,
  )

interface AppPackageIdCommRouteChildren {
  AppPackageIdCommAssetIdRoute: typeof AppPackageIdCommAssetIdRouteWithChildren
  AppPackageIdCommIndexRoute: typeof AppPackageIdCommIndexRoute
}

const AppPackageIdCommRouteChildren: AppPackageIdCommRouteChildren = {
  AppPackageIdCommAssetIdRoute: AppPackageIdCommAssetIdRouteWithChildren,
  AppPackageIdCommIndexRoute: AppPackageIdCommIndexRoute,
}

const AppPackageIdCommRouteWithChildren =
  AppPackageIdCommRoute._addFileChildren(AppPackageIdCommRouteChildren)

interface AppPackageIdTechRouteChildren {
  AppPackageIdTechDocsRoute: typeof AppPackageIdTechDocsRoute
  AppPackageIdTechPtcRoute: typeof AppPackageIdTechPtcRoute
  AppPackageIdTechIndexRoute: typeof AppPackageIdTechIndexRoute
}

const AppPackageIdTechRouteChildren: AppPackageIdTechRouteChildren = {
  AppPackageIdTechDocsRoute: AppPackageIdTechDocsRoute,
  AppPackageIdTechPtcRoute: AppPackageIdTechPtcRoute,
  AppPackageIdTechIndexRoute: AppPackageIdTechIndexRoute,
}

const AppPackageIdTechRouteWithChildren =
  AppPackageIdTechRoute._addFileChildren(AppPackageIdTechRouteChildren)

interface AppPackageIdRouteChildren {
  AppPackageIdCommRoute: typeof AppPackageIdCommRouteWithChildren
  AppPackageIdTechRoute: typeof AppPackageIdTechRouteWithChildren
  AppPackageIdIndexRoute: typeof AppPackageIdIndexRoute
}

const AppPackageIdRouteChildren: AppPackageIdRouteChildren = {
  AppPackageIdCommRoute: AppPackageIdCommRouteWithChildren,
  AppPackageIdTechRoute: AppPackageIdTechRouteWithChildren,
  AppPackageIdIndexRoute: AppPackageIdIndexRoute,
}

const AppPackageIdRouteWithChildren = AppPackageIdRoute._addFileChildren(
  AppPackageIdRouteChildren,
)

interface AppRouteChildren {
  AppAllProjectsRoute: typeof AppAllProjectsRoute
  AppVendorDbRoute: typeof AppVendorDbRoute
  AppIndexRoute: typeof AppIndexRoute
  AppPackageIdRoute: typeof AppPackageIdRouteWithChildren
  AppProjectIdRoute: typeof AppProjectIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAllProjectsRoute: AppAllProjectsRoute,
  AppVendorDbRoute: AppVendorDbRoute,
  AppIndexRoute: AppIndexRoute,
  AppPackageIdRoute: AppPackageIdRouteWithChildren,
  AppProjectIdRoute: AppProjectIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  CreateOrgRoute: CreateOrgRoute,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiWorkosCallbackRoute: ApiWorkosCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
